import type { Product } from "@/types";
import neemImg from "@/assets/product-neem.jpg";
import haldiImg from "@/assets/product-haldi.jpg";
import roseImg from "@/assets/product-rose.jpg";
import ubtanImg from "@/assets/product-ubtan.jpg";

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Neem Detox Face Pack",
    slug: "neem-detox-face-pack",
    tagline: "Deep purifying detox for clear, balanced skin",
    description: "Powered by wild-harvested neem, this therapeutic face pack deeply cleanses pores and combats acne-causing bacteria with Ayurvedic precision.",
    longDescription: "Ancient Ayurvedic texts extol neem as 'Sarva Roga Nivarini' — the curer of all ailments. Our Neem Detox Face Pack harnesses this time-honoured herb alongside sandalwood and turmeric to deliver deep-pore cleansing action. Rich in nimbidin and nimbin compounds, it actively combats acne, reduces oiliness and calms inflamed skin, revealing a visibly clearer, more balanced complexion.",
    price: 549,
    originalPrice: 749,
    images: [neemImg, "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&q=80", "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=80"],
    category: "Face Pack",
    tags: ["acne", "oily skin", "detox", "neem", "purifying"],
    ingredients: ["Neem Leaf Powder", "Sandalwood Powder", "Turmeric", "Tulsi Leaf Powder", "Multani Mitti", "Kaolin Clay", "Lodhra Bark"],
    benefits: ["Deep pore cleansing", "Reduces acne & blemishes", "Controls excess oil", "Brightens dull skin", "Calms inflammation", "Prevents future breakouts"],
    howToUse: ["Mix 1 tsp with rose water or plain water to form a paste", "Apply evenly to cleansed face & neck", "Leave for 15–20 minutes until semi-dry", "Rinse gently with lukewarm water", "Follow with TVAKSHRI Rose Glow serum", "Use 2–3 times per week"],
    skinType: ["Oily", "Combination", "Acne-prone", "Normal"],
    weight: "100g",
    inStock: true,
    stockCount: 48,
    rating: 4.8,
    reviewCount: 312,
    isBestseller: true,
    accentColor: "#2D6B14",
    bgColor: "#F0F7EC",
  },
  {
    id: "2",
    name: "Haldi Bright Face Pack",
    slug: "haldi-bright-face-pack",
    tagline: "Illuminate your radiance with sacred saffron turmeric",
    description: "A golden blend of Kashmiri saffron, certified organic turmeric and sandalwood that brightens, evens tone and bestows a lit-from-within luminosity.",
    longDescription: "The golden glow of turmeric has graced Indian beauty rituals for millennia. Our Haldi Bright Face Pack elevates this heritage with Kashmiri saffron strands, organic sandalwood powder and vitamin-rich papaya enzyme to create a brightening treatment that visibly diminishes dark spots, evens skin tone and imparts a signature golden radiance in just 3 weeks of consistent use.",
    price: 649,
    originalPrice: 899,
    images: [haldiImg, "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600&q=80", "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&q=80"],
    category: "Face Pack",
    tags: ["brightening", "anti-dark-spots", "glow", "turmeric", "saffron"],
    ingredients: ["Organic Turmeric (Curcuma longa)", "Kashmiri Saffron", "Sandalwood Powder", "Papaya Enzyme Powder", "Rice Flour", "Milk Powder", "Manjistha Root"],
    benefits: ["Brightens & evens skin tone", "Fades dark spots & hyperpigmentation", "Anti-ageing antioxidants", "Imparts golden glow", "Smoothens texture", "Boosts collagen production"],
    howToUse: ["Mix 1 tsp with milk, yogurt or rose water", "Apply to clean face avoiding eye area", "Massage gently in circular motions", "Leave for 15–20 minutes", "Rinse with cold water for pore tightening", "Use 3 times per week for best results"],
    skinType: ["All skin types", "Dull skin", "Hyperpigmentation", "Dry skin"],
    weight: "100g",
    inStock: true,
    stockCount: 62,
    rating: 4.9,
    reviewCount: 428,
    isBestseller: true,
    isNew: false,
    accentColor: "#E08B00",
    bgColor: "#FFF3D6",
  },
  {
    id: "3",
    name: "Rose Glow Face Pack",
    slug: "rose-glow-face-pack",
    tagline: "Petal-soft hydration and rosy luminescence",
    description: "Distilled from Bulgarian and Damask rose varieties, this luxuriously hydrating pack restores moisture, plumps fine lines and leaves skin with a dewy, rosy flush.",
    longDescription: "A symphony of Bulgarian rose petals, Damask rose water and cold-pressed rosehip oil — our Rose Glow Face Pack is a hydrating poem for parched skin. Enriched with hyaluronic acid microspheres and vitamin-C rich rosehip, it replenishes lost moisture barrier, softens fine lines and imparts a delicate rosy luminescence that lasts all day.",
    price: 699,
    originalPrice: 949,
    images: [roseImg, "https://images.unsplash.com/photo-1585232352617-e05c95e5e8a2?w=600&q=80", "https://images.unsplash.com/photo-1609840114035-3c981b782dfe?w=600&q=80"],
    category: "Face Pack",
    tags: ["hydrating", "glow", "anti-ageing", "rose", "dry skin"],
    ingredients: ["Dried Damask Rose Petal Powder", "Rosehip Oil", "Rose Water Powder", "Kaolin Clay", "Aloe Vera Powder", "Hyaluronic Acid Microspheres", "Vitamin E"],
    benefits: ["Deep hydration", "Plumps fine lines", "Rosy glow & luminescence", "Soothes sensitive skin", "Strengthens moisture barrier", "Natural fragrance from rose"],
    howToUse: ["Mix with rose water for maximum benefit", "Apply generously to face & décolletage", "Leave for 20 minutes", "Rinse with cool water", "Apply face oil or moisturiser while skin is still slightly damp", "Use 2–4 times per week"],
    skinType: ["Dry", "Normal", "Sensitive", "Mature skin"],
    weight: "100g",
    inStock: true,
    stockCount: 35,
    rating: 4.7,
    reviewCount: 276,
    isNew: true,
    accentColor: "#C94F4F",
    bgColor: "#FFF5F5",
  },
  {
    id: "4",
    name: "Rice Polish Powder",
    slug: "rice-polish-powder",
    tagline: "The Japanese-Ayurvedic secret to porcelain perfection",
    description: "Ultra-fine Japanese-inspired rice bran exfoliant blended with pearl powder and kojic acid for gentle polishing that reveals silky, luminous skin.",
    longDescription: "Inspired by the centuries-old secret of Japanese rice farmers known for their remarkably smooth skin, our Rice Polish Powder combines ultra-fine rice bran flour with precious pearl powder and natural kojic acid. This triple-action exfoliant gently buffs away dead cells, brightens post-acne marks and promotes silky, porcelain-smooth skin that catches light beautifully.",
    price: 499,
    originalPrice: 699,
    images: ["https://images.unsplash.com/photo-1619451334792-150fd785ee74?w=600&q=80", "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&q=80", "https://images.unsplash.com/photo-1612817288484-6f916006741a?w=600&q=80"],
    category: "Exfoliant",
    tags: ["exfoliant", "brightening", "smooth skin", "rice", "polish"],
    ingredients: ["Rice Bran Flour", "Pearl Powder", "Natural Kojic Acid", "Licorice Root Extract", "Green Tea Powder", "Vitamin C Derivatives", "Papaya Enzyme"],
    benefits: ["Gentle physical exfoliation", "Brightens & polishes", "Reduces dark spots", "Refines pores", "Silky-smooth texture", "Suitable for sensitive skin"],
    howToUse: ["Mix a small amount with cleanser or water to form a paste", "Apply to damp face with gentle circular motions", "Focus on congested areas (nose, chin, forehead)", "Rinse thoroughly with lukewarm water", "Follow with moisturiser", "Use 2 times per week only"],
    skinType: ["All skin types", "Sensitive", "Dull skin"],
    weight: "75g",
    inStock: true,
    stockCount: 89,
    rating: 4.6,
    reviewCount: 189,
    accentColor: "#8B6E40",
    bgColor: "#FFF8F0",
  },
  {
    id: "5",
    name: "Multani Purify Face Pack",
    slug: "multani-purify-face-pack",
    tagline: "Ancient earth clay — pure, powerful, perfecting",
    description: "Authentic Fuller's Earth sourced from mineral-rich deposits, blended with Vetiver and Brahmi to absorb excess sebum, minimise pores and restore skin equilibrium.",
    longDescription: "Multani Mitti (Fuller's Earth) has been a cornerstone of Ayurvedic beauty for over 5,000 years. Our Multani Purify Face Pack uses premium-grade clay sourced from authentic deposits, enriched with cooling vetiver root, brain-boosting brahmi and detoxifying charcoal. Together, they create an advanced oil-control treatment that purifies, mattifies and transforms congested skin.",
    price: 449,
    originalPrice: 599,
    images: ["https://images.unsplash.com/photo-1601042879364-f3947d3f9c16?w=600&q=80", "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=600&q=80", "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&q=80"],
    category: "Face Pack",
    tags: ["purifying", "oil control", "pores", "multani mitti", "clay"],
    ingredients: ["Premium Multani Mitti", "Vetiver Root Powder", "Brahmi Leaf Extract", "Activated Charcoal", "Camphor", "Neem Powder", "Tea Tree Leaf Powder"],
    benefits: ["Absorbs excess oil", "Minimises enlarged pores", "Removes blackheads", "Cools & refreshes skin", "Detoxifies skin cells", "Mattifies & balances"],
    howToUse: ["Mix with chilled rose water or cucumber juice", "Apply thick, even layer to face", "Leave for 15 minutes (do not let dry completely on dry skin)", "Rinse with cold water", "Tone with rose water after rinsing", "Use 1–2 times per week"],
    skinType: ["Oily", "Combination", "Normal", "Acne-prone"],
    weight: "100g",
    inStock: true,
    stockCount: 73,
    rating: 4.7,
    reviewCount: 234,
    accentColor: "#8B6340",
    bgColor: "#F5EDE0",
  },
  {
    id: "6",
    name: "Bridal Glow Ubtan",
    slug: "bridal-glow-ubtan",
    tagline: "The royal pre-bridal ritual for luminous, radiant skin",
    description: "A sacred blend of 21 Ayurvedic ingredients — chickpea flour, saffron, sandalwood and rose — used in royal bridal ceremonies for centuries to bestow a timeless glow.",
    longDescription: "Reserved for brides and special occasions in royal Indian households, Ubtan is the ultimate luxury skincare ritual. Our Bridal Glow Ubtan contains 21 premium Ayurvedic ingredients including Kashmiri saffron, organic chickpea flour, rose petals, sandalwood powder, and precious herbs like kumkumadi. Begin your 21-day bridal ritual 3 weeks before your special day for a breathtaking, luminous complexion that photographs beautifully.",
    price: 849,
    originalPrice: 1199,
    images: [ubtanImg, "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600&q=80", "https://images.unsplash.com/photo-1612817288484-6f916006741a?w=600&q=80"],
    category: "Ubtan",
    tags: ["bridal", "glow", "luxury", "ubtan", "special occasion", "saffron"],
    ingredients: ["Organic Chickpea Flour", "Kashmiri Saffron", "Sandalwood Powder", "Dried Rose Petals", "Turmeric", "Kumkumadi Tailam", "Lodhra", "Manjistha", "Amla Powder", "Ashwagandha"],
    benefits: ["Deep nourishment & glow", "Evens & brightens complexion", "Natural de-tanning", "Luxury fragrance from saffron & rose", "Full body use possible", "21-day transformation ritual"],
    howToUse: ["Mix 2 tsp with raw milk and a few drops of almond oil", "Apply generously to face, neck and body", "Let dry for 20–25 minutes", "Scrub gently while rinsing for exfoliation", "Rinse with lukewarm water", "Use daily 3 weeks before the occasion"],
    skinType: ["All skin types", "Bridal ritual", "Special occasions"],
    weight: "150g",
    inStock: true,
    stockCount: 28,
    rating: 4.9,
    reviewCount: 156,
    isBestseller: true,
    accentColor: "#9B0D0D",
    bgColor: "#FFE4E4",
  },
];

export const CATEGORIES = ["All", "Face Pack", "Exfoliant", "Ubtan"];

export const getProductBySlug = (slug: string): Product | undefined =>
  PRODUCTS.find((p) => p.slug === slug);

export const getRelatedProducts = (product: Product): Product[] =>
  PRODUCTS.filter((p) => p.id !== product.id && (p.category === product.category || p.tags.some((t) => product.tags.includes(t)))).slice(0, 3);
